default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  username: root

development:
  <<: *default
  database: code_resource_development

test:
  <<: *default
  database: code_resource_test

production:
  <<: *default
  database: code_resource_production
